# Generated by Django 3.2.5 on 2023-01-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home_poly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poly_index_001', models.CharField(blank=True, max_length=100000, verbose_name='文字')),
            ],
            options={
                'verbose_name': '塑膠首頁',
                'verbose_name_plural': '塑膠首頁',
            },
        ),
    ]
