# Generated by Django 3.2.5 on 2023-03-15 07:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyacetal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bcm_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcm_tit', models.CharField(blank=True, max_length=1000, verbose_name='產品標題')),
                ('bcm_num', models.CharField(blank=True, max_length=1000, verbose_name='產品型號')),
                ('bcm_img', models.CharField(blank=True, max_length=1000, verbose_name='產品圖片')),
                ('bcm_det', ckeditor.fields.RichTextField(blank=True, default='產品規格', max_length=10000, null=True, verbose_name='內容')),
            ],
            options={
                'verbose_name': 'Bag Converting',
                'verbose_name_plural': 'Bag Converting',
            },
        ),
        migrations.CreateModel(
            name='bes_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bes_tit', models.CharField(blank=True, max_length=1000, verbose_name='產品標題')),
                ('bes_num', models.CharField(blank=True, max_length=1000, verbose_name='產品型號')),
                ('bes_img', models.CharField(blank=True, max_length=1000, verbose_name='產品圖片')),
                ('bes_det', ckeditor.fields.RichTextField(blank=True, default='產品規格', max_length=10000, null=True, verbose_name='內容')),
            ],
            options={
                'verbose_name': 'Bubble Envelope',
                'verbose_name_plural': 'Bubble Envelope',
            },
        ),
        migrations.CreateModel(
            name='el_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('el_tit', models.CharField(blank=True, max_length=1000, verbose_name='產品標題')),
                ('el_num', models.CharField(blank=True, max_length=1000, verbose_name='產品型號')),
                ('el_img', models.CharField(blank=True, max_length=1000, verbose_name='產品圖片')),
                ('el_det', ckeditor.fields.RichTextField(blank=True, default='產品規格', max_length=10000, null=True, verbose_name='內容')),
            ],
            options={
                'verbose_name': 'Extrusion Line',
                'verbose_name_plural': 'Extrusion Line',
            },
        ),
        migrations.CreateModel(
            name='ma_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_tit', models.CharField(blank=True, max_length=1000, verbose_name='產品標題')),
                ('ma_num', models.CharField(blank=True, max_length=1000, verbose_name='產品型號')),
                ('ma_img', models.CharField(blank=True, max_length=1000, verbose_name='產品圖片')),
                ('ma_det', ckeditor.fields.RichTextField(blank=True, default='產品規格', max_length=10000, null=True, verbose_name='內容')),
            ],
            options={
                'verbose_name': 'Mask Application',
                'verbose_name_plural': 'Mask Application',
            },
        ),
        migrations.AlterModelOptions(
            name='ffmm_page',
            options={'verbose_name': 'File Folder', 'verbose_name_plural': 'File Folder'},
        ),
    ]
