# Generated by Django 3.2.5 on 2023-03-06 07:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyacetal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ffmm_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ffmm_tit', models.CharField(blank=True, max_length=100000, verbose_name='產品標題')),
                ('ffmm_num', models.CharField(blank=True, max_length=100000, verbose_name='產品型號')),
                ('ffmm_img', models.CharField(blank=True, max_length=100000, verbose_name='產品圖片')),
                ('ffmm_det', ckeditor.fields.RichTextField(blank=True, default='產品規格', max_length=10000, null=True, verbose_name='內容')),
            ],
            options={
                'verbose_name': '塑膠資料夾',
                'verbose_name_plural': '塑膠資料夾',
            },
        ),
        migrations.AddField(
            model_name='home_poly',
            name='poly_index_002',
            field=models.CharField(blank=True, max_length=100000, verbose_name='輪播圖片-5'),
        ),
        migrations.AddField(
            model_name='home_poly',
            name='poly_index_003',
            field=models.CharField(blank=True, max_length=100000, verbose_name='輪播圖片-2'),
        ),
        migrations.AddField(
            model_name='home_poly',
            name='poly_index_004',
            field=models.CharField(blank=True, max_length=100000, verbose_name='輪播圖片-3'),
        ),
    ]
