# Generated by Django 3.2.5 on 2023-03-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyacetal', '0002_auto_20230306_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_poly',
            name='poly_index_005',
            field=models.CharField(blank=True, max_length=100000, verbose_name='輪播圖片-4'),
        ),
        migrations.AddField(
            model_name='home_poly',
            name='poly_index_006',
            field=models.CharField(blank=True, max_length=100000, verbose_name='輪播圖片-5'),
        ),
        migrations.AlterField(
            model_name='home_poly',
            name='poly_index_002',
            field=models.CharField(blank=True, max_length=100000, verbose_name='輪播圖片-1'),
        ),
    ]
