# Generated by Django 3.2.5 on 2023-03-07 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polyacetal', '0003_auto_20230306_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ffmm_page',
            options={'verbose_name': 'file folder', 'verbose_name_plural': 'file folder'},
        ),
        migrations.AlterModelOptions(
            name='home_poly',
            options={'verbose_name': 'poly-home', 'verbose_name_plural': 'poly-home'},
        ),
    ]
