# Generated by Django 3.2.5 on 2023-03-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polyacetal', '0004_auto_20230307_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ffmm_page',
            name='ffmm_img',
            field=models.CharField(blank=True, max_length=1000, verbose_name='產品圖片'),
        ),
        migrations.AlterField(
            model_name='ffmm_page',
            name='ffmm_num',
            field=models.CharField(blank=True, max_length=1000, verbose_name='產品型號'),
        ),
        migrations.AlterField(
            model_name='ffmm_page',
            name='ffmm_tit',
            field=models.CharField(blank=True, max_length=1000, verbose_name='產品標題'),
        ),
        migrations.AlterField(
            model_name='home_poly',
            name='poly_index_001',
            field=models.CharField(blank=True, max_length=1000, verbose_name='文字'),
        ),
        migrations.AlterField(
            model_name='home_poly',
            name='poly_index_002',
            field=models.CharField(blank=True, max_length=1000, verbose_name='輪播圖片-1'),
        ),
        migrations.AlterField(
            model_name='home_poly',
            name='poly_index_003',
            field=models.CharField(blank=True, max_length=1000, verbose_name='輪播圖片-2'),
        ),
        migrations.AlterField(
            model_name='home_poly',
            name='poly_index_004',
            field=models.CharField(blank=True, max_length=1000, verbose_name='輪播圖片-3'),
        ),
        migrations.AlterField(
            model_name='home_poly',
            name='poly_index_005',
            field=models.CharField(blank=True, max_length=1000, verbose_name='輪播圖片-4'),
        ),
        migrations.AlterField(
            model_name='home_poly',
            name='poly_index_006',
            field=models.CharField(blank=True, max_length=1000, verbose_name='輪播圖片-5'),
        ),
    ]
