# Generated by Django 3.2.5 on 2022-11-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plat_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_phn_001', models.CharField(blank=True, max_length=100000, verbose_name='聯絡電話')),
                ('plat_adr_001', models.CharField(blank=True, max_length=100000, verbose_name='聯絡地址')),
                ('plat_mail_001', models.CharField(blank=True, max_length=100000, verbose_name='聯絡信箱')),
            ],
            options={
                'verbose_name': '基本資訊',
                'verbose_name_plural': '基本資訊',
            },
        ),
        migrations.CreateModel(
            name='plat_index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop_ph_001', models.CharField(blank=True, max_length=100000, verbose_name='插入圖片')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
    ]
