from django.urls import path
from .views import (
   IndexListView,
   Welding_01View,
   Welding_02View,
   cpn_01View,
   mta_01View,
   sys_01View,
   qa_01View,
   ca_01View,
   consumer_01View,
   battery_01View,
   electronics_01View,
   medical_01View,
   hygiene_01View,
   automotive_01View,
   automation_01View,
   food_01View,
   IndexListView_en,
   Welding_01View_en,
   Welding_02View_en,
   cpn_01View_en,
   mta_01View_en,
   sys_01View_en,
   qa_01View_en,
   ca_01View_en,
   consumer_01View_en,
   battery_01View_en,
   electronics_01View_en,
   medical_01View_en,
   hygiene_01View_en,
   automotive_01View_en,
   automation_01View_en,
   food_01View_en,
)

app_name = 'herrmann'
urlpatterns = [
    path('', IndexListView.as_view(), name="index"),
    path('tw', IndexListView.as_view(), name="tw"),
    path('welding', Welding_02View.as_view(), name="weld-2"),
    path('components', cpn_01View.as_view(), name="cpn"),
    path('metal', mta_01View.as_view(), name="mta"),
    path('system', sys_01View.as_view(), name="sys"),
    path('qa', qa_01View.as_view(), name="qa"),
    path('ca', ca_01View.as_view(), name="ca"),
    path('co', consumer_01View.as_view(), name="co"),
    path('ba', battery_01View.as_view(), name="ba"),
    path('el', electronics_01View.as_view(), name="el"),
    path('me', medical_01View.as_view(), name="me"),
    path('hy', hygiene_01View.as_view(), name="hy"),
    path('mo', automotive_01View.as_view(), name="mo"),
    path('ma', automation_01View.as_view(), name="ma"),
    path('fo', food_01View.as_view(), name="fo"),

    path('en', IndexListView_en.as_view(), name="en"),
    path('en/welding', Welding_02View_en.as_view(), name="en-weld-2"),
    path('en/components', cpn_01View_en.as_view(), name="en-cpn"),
    path('en/metal', mta_01View_en.as_view(), name="en-mta"),
    path('en/system', sys_01View_en.as_view(), name="en-sys"),
    path('en/qa', qa_01View_en.as_view(), name="en-qa"),
    path('en/ca', ca_01View_en.as_view(), name="en-ca"),
    path('en/co', consumer_01View_en.as_view(), name="en-co"),
    path('en/ba', battery_01View_en.as_view(), name="en-ba"),
    path('en/el', electronics_01View_en.as_view(), name="en-el"),
    path('en/me', medical_01View_en.as_view(), name="en-me"),
    path('en/hy', hygiene_01View_en.as_view(), name="en-hy"),
    path('en/mo', automotive_01View_en.as_view(), name="en-mo"),
    path('en/ma', automation_01View_en.as_view(), name="en-ma"),
    path('en/fo', food_01View_en.as_view(), name="en-fo"),
]