# Generated by Django 3.2.5 on 2022-03-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid_txt_001', models.CharField(blank=True, max_length=1000, verbose_name='左下')),
                ('mid_txt_002', models.CharField(blank=True, max_length=1000, verbose_name='中下')),
                ('mid_tit_001', models.CharField(blank=True, max_length=1000, verbose_name='右下-標題')),
                ('mid_txt_003', models.CharField(blank=True, max_length=1000, verbose_name='右下')),
                ('phn_001', models.CharField(blank=True, max_length=1000, verbose_name='聯絡電話')),
                ('adr_001', models.CharField(blank=True, max_length=1000, verbose_name='聯絡地址')),
                ('mail_001', models.CharField(blank=True, max_length=1000, verbose_name='聯絡信箱')),
            ],
            options={
                'verbose_name': '首頁',
                'verbose_name_plural': '首頁',
            },
        ),
    ]
