# Generated by Django 3.2.5 on 2022-03-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herrmann', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_01',
            name='mid_tit_002',
            field=models.CharField(blank=True, max_length=1000, verbose_name='中上-標題'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_tit_003',
            field=models.CharField(blank=True, max_length=1000, verbose_name='右上-標題'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_tit_004',
            field=models.CharField(blank=True, max_length=1000, verbose_name='左下-標題'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_tit_005',
            field=models.CharField(blank=True, max_length=1000, verbose_name='中下-標題'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_tit_006',
            field=models.CharField(blank=True, max_length=1000, verbose_name='右下-標題'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_txt_004',
            field=models.CharField(blank=True, max_length=1000, verbose_name='左下'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_txt_005',
            field=models.CharField(blank=True, max_length=1000, verbose_name='中下'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_txt_006',
            field=models.CharField(blank=True, max_length=1000, verbose_name='右下'),
        ),
        migrations.AlterField(
            model_name='index_01',
            name='mid_tit_001',
            field=models.CharField(blank=True, max_length=1000, verbose_name='左上-標題'),
        ),
        migrations.AlterField(
            model_name='index_01',
            name='mid_txt_001',
            field=models.CharField(blank=True, max_length=1000, verbose_name='左上'),
        ),
        migrations.AlterField(
            model_name='index_01',
            name='mid_txt_002',
            field=models.CharField(blank=True, max_length=1000, verbose_name='中上'),
        ),
        migrations.AlterField(
            model_name='index_01',
            name='mid_txt_003',
            field=models.CharField(blank=True, max_length=1000, verbose_name='右上'),
        ),
    ]
