# Generated by Django 3.2.5 on 2022-03-17 11:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herrmann', '0002_auto_20220308_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='welding_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welding_tit_001', models.CharField(blank=True, max_length=1000, verbose_name='產品特色標題-1')),
                ('welding_txt_001', models.CharField(blank=True, max_length=1000, verbose_name='產品特色內容-1')),
                ('welding_tit_002', models.CharField(blank=True, max_length=1000, verbose_name='產品特色標題-2')),
                ('welding_txt_002', models.CharField(blank=True, max_length=1000, verbose_name='產品特色內容-2')),
                ('welding_tit_003', models.CharField(blank=True, max_length=1000, verbose_name='產品特色標題-3')),
                ('welding_txt_003', models.CharField(blank=True, max_length=1000, verbose_name='產品特色內容-3')),
            ],
            options={
                'verbose_name': 'welding-簡介',
                'verbose_name_plural': 'welding-簡介',
            },
        ),
        migrations.CreateModel(
            name='welding_02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welding_tit', models.CharField(blank=True, max_length=1000, verbose_name='產品名稱')),
                ('welding_cont', models.CharField(blank=True, max_length=1000, verbose_name='主要產品說明')),
                ('welding_img_001', models.CharField(blank=True, max_length=1000, verbose_name='產品圖片-1')),
                ('welding_seri_001', models.CharField(blank=True, max_length=1000, verbose_name='產品系列-1')),
                ('welding_seri_cont_001', ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=1000, null=True, verbose_name='內容')),
                ('welding_img_002', models.CharField(blank=True, max_length=1000, verbose_name='產品圖片-2')),
                ('welding_seri_002', models.CharField(blank=True, max_length=1000, verbose_name='產品系列-2')),
                ('welding_seri_cont_002', ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=1000, null=True, verbose_name='內容')),
                ('welding_img_003', models.CharField(blank=True, max_length=1000, verbose_name='產品圖片-3')),
                ('welding_seri_003', models.CharField(blank=True, max_length=1000, verbose_name='產品系列-3')),
                ('welding_seri_cont_003', ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=1000, null=True, verbose_name='內容')),
                ('welding_img_004', models.CharField(blank=True, max_length=1000, verbose_name='產品圖片-4')),
                ('welding_seri_004', models.CharField(blank=True, max_length=1000, verbose_name='產品系列-4')),
                ('welding_seri_cont_004', ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=1000, null=True, verbose_name='內容')),
                ('welding_img_005', models.CharField(blank=True, max_length=1000, verbose_name='產品圖片-5')),
                ('welding_seri_005', models.CharField(blank=True, max_length=1000, verbose_name='產品系列-5')),
                ('welding_seri_cont_005', ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=1000, null=True, verbose_name='內容')),
            ],
            options={
                'verbose_name': 'welding-品項',
                'verbose_name_plural': 'welding-品項',
            },
        ),
    ]
