# Generated by Django 3.2.5 on 2022-03-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herrmann', '0003_welding_01_welding_02'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welding_02',
            old_name='welding_seri_001',
            new_name='welding_seri_001_1',
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_2',
            field=models.CharField(blank=True, max_length=1000, verbose_name='產品系列-2'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_3',
            field=models.CharField(blank=True, max_length=1000, verbose_name='產品系列-3'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_4',
            field=models.CharField(blank=True, max_length=1000, verbose_name='產品系列-4'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_tit_01',
            field=models.CharField(blank=True, max_length=1000, verbose_name='產品系列-標題'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_tit_02',
            field=models.CharField(blank=True, max_length=1000, verbose_name='產品系列-標題'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_tit_03',
            field=models.CharField(blank=True, max_length=1000, verbose_name='產品系列-標題'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_tit_04',
            field=models.CharField(blank=True, max_length=1000, verbose_name='產品系列-標題'),
        ),
    ]
