# Generated by Django 3.2.5 on 2022-03-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herrmann', '0004_auto_20220317_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='welding_02',
            name='welding_cont_03',
            field=models.CharField(blank=True, max_length=1000, verbose_name='主要產品說明'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_tit_02',
            field=models.CharField(blank=True, max_length=1000, verbose_name='產品名稱'),
        ),
    ]
