# Generated by Django 3.2.5 on 2022-03-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herrmann', '0006_auto_20220318_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welding_02',
            name='welding_seri_cont_001',
        ),
    ]
