# Generated by Django 3.2.5 on 2022-03-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herrmann', '0007_remove_welding_02_welding_seri_cont_001'),
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phn_001', models.CharField(blank=True, max_length=1000, verbose_name='聯絡電話')),
                ('adr_001', models.CharField(blank=True, max_length=1000, verbose_name='聯絡地址')),
                ('mail_001', models.CharField(blank=True, max_length=1000, verbose_name='聯絡信箱')),
            ],
            options={
                'verbose_name': '基本資訊',
                'verbose_name_plural': '基本資訊',
            },
        ),
    ]
