# Generated by Django 3.2.5 on 2022-03-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herrmann', '0008_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index_01',
            name='adr_001',
        ),
        migrations.RemoveField(
            model_name='index_01',
            name='mail_001',
        ),
        migrations.RemoveField(
            model_name='index_01',
            name='phn_001',
        ),
    ]
