# Generated by Django 3.2.5 on 2022-03-23 10:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herrmann', '0009_auto_20220323_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='cpn_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpn_tit', models.CharField(blank=True, max_length=1000, verbose_name='產品名稱')),
                ('cpn_cont', ckeditor.fields.RichTextField(blank=True, max_length=1000, verbose_name='主要產品說明')),
                ('cpn_img_001', models.CharField(blank=True, max_length=1000, verbose_name='產品圖片-1')),
                ('cpn_seri_001_tit_01', models.CharField(blank=True, max_length=1000, verbose_name='產品系列-標題-1')),
                ('cpn_seri_001_1', ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=10000, null=True, verbose_name='內容')),
                ('cpn_seri_001_tit_02', models.CharField(blank=True, max_length=1000, verbose_name='產品系列-標題-2')),
                ('cpn_seri_001_2', ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=10000, null=True, verbose_name='內容')),
                ('cpn_seri_001_tit_03', models.CharField(blank=True, max_length=1000, verbose_name='產品系列-標題-3')),
                ('cpn_seri_001_3', ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=10000, null=True, verbose_name='內容')),
                ('cpn_seri_001_tit_04', models.CharField(blank=True, max_length=1000, verbose_name='產品系列-標題-4')),
                ('cpn_seri_001_4', ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=10000, null=True, verbose_name='內容')),
            ],
            options={
                'verbose_name': 'components-品項',
                'verbose_name_plural': 'components-品項',
            },
        ),
    ]
