# Generated by Django 3.2.5 on 2022-04-11 04:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herrmann', '0012_sys_01'),
    ]

    operations = [
        migrations.CreateModel(
            name='bc_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_tit', models.CharField(blank=True, max_length=100000, verbose_name='產品名稱')),
                ('bc_cont', ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='主要產品說明')),
                ('bc_img_001', models.CharField(blank=True, max_length=100000, verbose_name='產品圖片-1')),
                ('bc_img_002', models.CharField(blank=True, max_length=100000, verbose_name='產品圖片-1')),
                ('bc_img_003', models.CharField(blank=True, max_length=100000, verbose_name='產品圖片-1')),
                ('bc_img_004', models.CharField(blank=True, max_length=100000, verbose_name='產品圖片-1')),
                ('bc_img_005', models.CharField(blank=True, max_length=100000, verbose_name='產品圖片-1')),
                ('bc_img_006', models.CharField(blank=True, max_length=100000, verbose_name='產品圖片-1')),
                ('bc_img_007', models.CharField(blank=True, max_length=100000, verbose_name='產品圖片-1')),
                ('bc_img_008', models.CharField(blank=True, max_length=100000, verbose_name='產品圖片-1')),
                ('bc_img_009', models.CharField(blank=True, max_length=100000, verbose_name='產品圖片-1')),
                ('bc_img_010', models.CharField(blank=True, max_length=100000, verbose_name='產品圖片-1')),
            ],
            options={
                'verbose_name': 'Branches-超音波應用',
                'verbose_name_plural': 'Branches-超音波應用',
            },
        ),
        migrations.AlterModelOptions(
            name='sys_01',
            options={'verbose_name': 'application-應用', 'verbose_name_plural': 'application-應用'},
        ),
        migrations.AlterField(
            model_name='cpn_01',
            name='cpn_cont',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='主要產品說明'),
        ),
        migrations.AlterField(
            model_name='cpn_01',
            name='cpn_img_001',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品圖片-1'),
        ),
        migrations.AlterField(
            model_name='cpn_01',
            name='cpn_seri_001_1',
            field=ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='cpn_01',
            name='cpn_seri_001_2',
            field=ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='cpn_01',
            name='cpn_seri_001_3',
            field=ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='cpn_01',
            name='cpn_seri_001_4',
            field=ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='cpn_01',
            name='cpn_seri_001_tit_01',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品系列-標題-1'),
        ),
        migrations.AlterField(
            model_name='cpn_01',
            name='cpn_seri_001_tit_02',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品系列-標題-2'),
        ),
        migrations.AlterField(
            model_name='cpn_01',
            name='cpn_seri_001_tit_03',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品系列-標題-3'),
        ),
        migrations.AlterField(
            model_name='cpn_01',
            name='cpn_seri_001_tit_04',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品系列-標題-4'),
        ),
        migrations.AlterField(
            model_name='cpn_01',
            name='cpn_tit',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品名稱'),
        ),
        migrations.AlterField(
            model_name='home',
            name='adr_001',
            field=models.CharField(blank=True, max_length=100000, verbose_name='聯絡地址'),
        ),
        migrations.AlterField(
            model_name='home',
            name='mail_001',
            field=models.CharField(blank=True, max_length=100000, verbose_name='聯絡信箱'),
        ),
        migrations.AlterField(
            model_name='home',
            name='phn_001',
            field=models.CharField(blank=True, max_length=100000, verbose_name='聯絡電話'),
        ),
        migrations.AlterField(
            model_name='index_01',
            name='mid_tit_001',
            field=models.CharField(blank=True, max_length=100000, verbose_name='左上-標題'),
        ),
        migrations.AlterField(
            model_name='index_01',
            name='mid_tit_002',
            field=models.CharField(blank=True, max_length=100000, verbose_name='中上-標題'),
        ),
        migrations.AlterField(
            model_name='index_01',
            name='mid_tit_003',
            field=models.CharField(blank=True, max_length=100000, verbose_name='右上-標題'),
        ),
        migrations.AlterField(
            model_name='index_01',
            name='mid_tit_004',
            field=models.CharField(blank=True, max_length=100000, verbose_name='左下-標題'),
        ),
        migrations.AlterField(
            model_name='index_01',
            name='mid_tit_005',
            field=models.CharField(blank=True, max_length=100000, verbose_name='中下-標題'),
        ),
        migrations.AlterField(
            model_name='index_01',
            name='mid_tit_006',
            field=models.CharField(blank=True, max_length=100000, verbose_name='右下-標題'),
        ),
        migrations.AlterField(
            model_name='index_01',
            name='mid_txt_001',
            field=models.CharField(blank=True, max_length=100000, verbose_name='左上'),
        ),
        migrations.AlterField(
            model_name='index_01',
            name='mid_txt_002',
            field=models.CharField(blank=True, max_length=100000, verbose_name='中上'),
        ),
        migrations.AlterField(
            model_name='index_01',
            name='mid_txt_003',
            field=models.CharField(blank=True, max_length=100000, verbose_name='右上'),
        ),
        migrations.AlterField(
            model_name='index_01',
            name='mid_txt_004',
            field=models.CharField(blank=True, max_length=100000, verbose_name='左下'),
        ),
        migrations.AlterField(
            model_name='index_01',
            name='mid_txt_005',
            field=models.CharField(blank=True, max_length=100000, verbose_name='中下'),
        ),
        migrations.AlterField(
            model_name='index_01',
            name='mid_txt_006',
            field=models.CharField(blank=True, max_length=100000, verbose_name='右下'),
        ),
        migrations.AlterField(
            model_name='mta_01',
            name='mta_cont',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='主要產品說明'),
        ),
        migrations.AlterField(
            model_name='mta_01',
            name='mta_img_001',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品圖片-1'),
        ),
        migrations.AlterField(
            model_name='mta_01',
            name='mta_seri_001_1',
            field=ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='mta_01',
            name='mta_seri_001_2',
            field=ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='mta_01',
            name='mta_seri_001_3',
            field=ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='mta_01',
            name='mta_seri_001_4',
            field=ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='mta_01',
            name='mta_seri_001_tit_01',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品系列-標題-1'),
        ),
        migrations.AlterField(
            model_name='mta_01',
            name='mta_seri_001_tit_02',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品系列-標題-2'),
        ),
        migrations.AlterField(
            model_name='mta_01',
            name='mta_seri_001_tit_03',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品系列-標題-3'),
        ),
        migrations.AlterField(
            model_name='mta_01',
            name='mta_seri_001_tit_04',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品系列-標題-4'),
        ),
        migrations.AlterField(
            model_name='mta_01',
            name='mta_tit',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品名稱'),
        ),
        migrations.AlterField(
            model_name='sys_01',
            name='sys_cont',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='主要產品說明'),
        ),
        migrations.AlterField(
            model_name='sys_01',
            name='sys_img_001',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品圖片-1'),
        ),
        migrations.AlterField(
            model_name='sys_01',
            name='sys_seri_001_1',
            field=ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='sys_01',
            name='sys_seri_001_2',
            field=ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='sys_01',
            name='sys_seri_001_3',
            field=ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='sys_01',
            name='sys_seri_001_4',
            field=ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='sys_01',
            name='sys_seri_001_tit_01',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品系列-標題-1'),
        ),
        migrations.AlterField(
            model_name='sys_01',
            name='sys_seri_001_tit_02',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品系列-標題-2'),
        ),
        migrations.AlterField(
            model_name='sys_01',
            name='sys_seri_001_tit_03',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品系列-標題-3'),
        ),
        migrations.AlterField(
            model_name='sys_01',
            name='sys_seri_001_tit_04',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品系列-標題-4'),
        ),
        migrations.AlterField(
            model_name='sys_01',
            name='sys_tit',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品名稱'),
        ),
        migrations.AlterField(
            model_name='welding_01',
            name='welding_tit_001',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品特色標題-1'),
        ),
        migrations.AlterField(
            model_name='welding_01',
            name='welding_tit_002',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品特色標題-2'),
        ),
        migrations.AlterField(
            model_name='welding_01',
            name='welding_tit_003',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品特色標題-3'),
        ),
        migrations.AlterField(
            model_name='welding_01',
            name='welding_txt_001',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='產品特色內容-1'),
        ),
        migrations.AlterField(
            model_name='welding_01',
            name='welding_txt_002',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='產品特色內容-2'),
        ),
        migrations.AlterField(
            model_name='welding_01',
            name='welding_txt_003',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='產品特色內容-3'),
        ),
        migrations.AlterField(
            model_name='welding_02',
            name='welding_cont',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='主要產品說明'),
        ),
        migrations.AlterField(
            model_name='welding_02',
            name='welding_img_001',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品圖片-1'),
        ),
        migrations.AlterField(
            model_name='welding_02',
            name='welding_seri_001_1',
            field=ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='welding_02',
            name='welding_seri_001_2',
            field=ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='welding_02',
            name='welding_seri_001_3',
            field=ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='welding_02',
            name='welding_seri_001_4',
            field=ckeditor.fields.RichTextField(blank=True, default='文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='welding_02',
            name='welding_seri_001_tit_01',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品系列-標題-1'),
        ),
        migrations.AlterField(
            model_name='welding_02',
            name='welding_seri_001_tit_02',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品系列-標題-2'),
        ),
        migrations.AlterField(
            model_name='welding_02',
            name='welding_seri_001_tit_03',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品系列-標題-3'),
        ),
        migrations.AlterField(
            model_name='welding_02',
            name='welding_seri_001_tit_04',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品系列-標題-4'),
        ),
        migrations.AlterField(
            model_name='welding_02',
            name='welding_tit',
            field=models.CharField(blank=True, max_length=100000, verbose_name='產品名稱'),
        ),
    ]
