# Generated by Django 3.2.5 on 2022-04-11 08:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herrmann', '0013_auto_20220411_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='qa_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qa_tit', models.CharField(blank=True, max_length=100000, verbose_name='Ｑ:')),
                ('qa_cont', ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='A:')),
            ],
            options={
                'verbose_name': 'QA',
                'verbose_name_plural': 'QA',
            },
        ),
    ]
