# Generated by Django 3.2.5 on 2022-04-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herrmann', '0015_ca_01'),
    ]

    operations = [
        migrations.CreateModel(
            name='automation_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automation_tit', models.CharField(blank=True, max_length=100000, verbose_name='標題')),
                ('automation_ctn', models.CharField(blank=True, max_length=100000, verbose_name='內容')),
                ('automation_pho', models.CharField(blank=True, max_length=100000, verbose_name='圖片')),
            ],
            options={
                'verbose_name': 'automation',
                'verbose_name_plural': 'automation',
            },
        ),
        migrations.CreateModel(
            name='automotive_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automotive_tit', models.CharField(blank=True, max_length=100000, verbose_name='標題')),
                ('automotive_ctn', models.CharField(blank=True, max_length=100000, verbose_name='內容')),
                ('automotive_pho', models.CharField(blank=True, max_length=100000, verbose_name='圖片')),
            ],
            options={
                'verbose_name': 'automotive',
                'verbose_name_plural': 'automotive',
            },
        ),
        migrations.CreateModel(
            name='battery_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_tit', models.CharField(blank=True, max_length=100000, verbose_name='標題')),
                ('battery_ctn', models.CharField(blank=True, max_length=100000, verbose_name='內容')),
                ('battery_pho', models.CharField(blank=True, max_length=100000, verbose_name='圖片')),
            ],
            options={
                'verbose_name': 'battery',
                'verbose_name_plural': 'battery',
            },
        ),
        migrations.CreateModel(
            name='consumer_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_tit', models.CharField(blank=True, max_length=100000, verbose_name='標題')),
                ('consumer_ctn', models.CharField(blank=True, max_length=100000, verbose_name='內容')),
                ('consumer_pho', models.CharField(blank=True, max_length=100000, verbose_name='圖片')),
            ],
            options={
                'verbose_name': 'consumer',
                'verbose_name_plural': 'consumer',
            },
        ),
        migrations.CreateModel(
            name='electronics_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronics_tit', models.CharField(blank=True, max_length=100000, verbose_name='標題')),
                ('electronics_ctn', models.CharField(blank=True, max_length=100000, verbose_name='內容')),
                ('electronics_pho', models.CharField(blank=True, max_length=100000, verbose_name='圖片')),
            ],
            options={
                'verbose_name': 'electronics',
                'verbose_name_plural': 'electronics',
            },
        ),
        migrations.CreateModel(
            name='food_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_tit', models.CharField(blank=True, max_length=100000, verbose_name='標題')),
                ('food_ctn', models.CharField(blank=True, max_length=100000, verbose_name='內容')),
                ('food_pho', models.CharField(blank=True, max_length=100000, verbose_name='圖片')),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Food',
            },
        ),
        migrations.CreateModel(
            name='hygiene_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hygiene_tit', models.CharField(blank=True, max_length=100000, verbose_name='標題')),
                ('hygiene_ctn', models.CharField(blank=True, max_length=100000, verbose_name='內容')),
                ('hygiene_pho', models.CharField(blank=True, max_length=100000, verbose_name='圖片')),
            ],
            options={
                'verbose_name': 'hygiene',
                'verbose_name_plural': 'hygiene',
            },
        ),
        migrations.CreateModel(
            name='medical_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_tit', models.CharField(blank=True, max_length=100000, verbose_name='標題')),
                ('medical_ctn', models.CharField(blank=True, max_length=100000, verbose_name='內容')),
                ('medical_pho', models.CharField(blank=True, max_length=100000, verbose_name='圖片')),
            ],
            options={
                'verbose_name': 'medical',
                'verbose_name_plural': 'medical',
            },
        ),
        migrations.AlterModelOptions(
            name='mta_01',
            options={'verbose_name': '對應超音波金屬熔接', 'verbose_name_plural': '對應超音波金屬熔接'},
        ),
        migrations.AlterModelOptions(
            name='sys_01',
            options={'verbose_name': '對應超音波集成系統', 'verbose_name_plural': '對應超音波集成系統'},
        ),
    ]
