# Generated by Django 3.2.5 on 2022-04-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herrmann', '0016_auto_20220426_0634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_01',
            old_name='food_pho',
            new_name='food_pho_01',
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_02',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_03',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_04',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_05',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_06',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_07',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_08',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
    ]
