# Generated by Django 3.2.5 on 2022-04-27 04:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herrmann', '0017_auto_20220426_0643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bc_01',
            options={'ordering': ['id'], 'verbose_name': 'Branches-超音波應用', 'verbose_name_plural': 'Branches-超音波應用'},
        ),
        migrations.AlterModelOptions(
            name='cpn_01',
            options={'ordering': ['id'], 'verbose_name': 'components-品項', 'verbose_name_plural': 'components-品項'},
        ),
        migrations.AlterModelOptions(
            name='mta_01',
            options={'ordering': ['id'], 'verbose_name': '對應超音波金屬熔接', 'verbose_name_plural': '對應超音波金屬熔接'},
        ),
        migrations.AlterModelOptions(
            name='qa_01',
            options={'ordering': ['id'], 'verbose_name': 'QA', 'verbose_name_plural': 'QA'},
        ),
        migrations.AlterModelOptions(
            name='sys_01',
            options={'ordering': ['id'], 'verbose_name': '對應超音波集成系統', 'verbose_name_plural': '對應超音波集成系統'},
        ),
        migrations.AlterModelOptions(
            name='welding_02',
            options={'ordering': ['id'], 'verbose_name': 'welding-品項', 'verbose_name_plural': 'welding-品項'},
        ),
        migrations.RenameField(
            model_name='automation_01',
            old_name='automation_pho',
            new_name='automation_pho_01',
        ),
        migrations.RenameField(
            model_name='automotive_01',
            old_name='automotive_pho',
            new_name='automotive_pho_01',
        ),
        migrations.RenameField(
            model_name='battery_01',
            old_name='battery_pho',
            new_name='battery_pho_01',
        ),
        migrations.RenameField(
            model_name='consumer_01',
            old_name='consumer_pho',
            new_name='consumer_pho_01',
        ),
        migrations.RenameField(
            model_name='electronics_01',
            old_name='electronics_pho',
            new_name='electronics_pho_01',
        ),
        migrations.RenameField(
            model_name='hygiene_01',
            old_name='hygiene_pho',
            new_name='hygiene_pho_01',
        ),
        migrations.RenameField(
            model_name='medical_01',
            old_name='medical_pho',
            new_name='medical_pho_01',
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_02',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_03',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_04',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_05',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_06',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_07',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_08',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_02',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_03',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_04',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_05',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_06',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_07',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_08',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_02',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_03',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_04',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_05',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_06',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_07',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_08',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_02',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_03',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_04',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_05',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_06',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_07',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_08',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_02',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_03',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_04',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_05',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_06',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_07',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_08',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_02',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_03',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_04',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_05',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_06',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_07',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_08',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_02',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_03',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_04',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_05',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_06',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_07',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_08',
            field=models.CharField(blank=True, max_length=100000, verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='automation_01',
            name='automation_ctn',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='automotive_01',
            name='automotive_ctn',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='battery_01',
            name='battery_ctn',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='consumer_01',
            name='consumer_ctn',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='electronics_01',
            name='electronics_ctn',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='food_01',
            name='food_ctn',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='hygiene_01',
            name='hygiene_ctn',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='medical_01',
            name='medical_ctn',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='內容'),
        ),
    ]
