# Generated by Django 3.2.5 on 2022-05-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herrmann', '0018_auto_20220427_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_01',
            name='mid_tit_007',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-左上-標題'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_tit_008',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-中上-標題'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_tit_009',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-右上-標題'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_tit_010',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-左下-標題'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_tit_011',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-中下-標題'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_tit_012',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-右下-標題'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_txt_007',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-左上'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_txt_008',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-中上'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_txt_009',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-右上'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_txt_010',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-左下'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_txt_011',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-中下'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_txt_012',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-右下'),
        ),
    ]
