# Generated by Django 3.2.5 on 2022-05-16 07:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herrmann', '0019_auto_20220507_0717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bc_01',
            options={'ordering': ['id'], 'verbose_name': 'Branches', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='cpn_01',
            options={'ordering': ['id'], 'verbose_name': 'components', 'verbose_name_plural': 'components'},
        ),
        migrations.AlterModelOptions(
            name='index_01',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Home'},
        ),
        migrations.AlterModelOptions(
            name='mta_01',
            options={'ordering': ['id'], 'verbose_name': 'metal', 'verbose_name_plural': 'metal'},
        ),
        migrations.AlterModelOptions(
            name='sys_01',
            options={'ordering': ['id'], 'verbose_name': 'system', 'verbose_name_plural': 'system'},
        ),
        migrations.AlterModelOptions(
            name='welding_02',
            options={'ordering': ['id'], 'verbose_name': 'welding', 'verbose_name_plural': 'welding'},
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_ctn_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='EN-內容'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_01_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_02_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_03_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_04_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_05_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_06_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_07_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_08_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_tit_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-標題'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_ctn_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='EN-內容'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_01_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_02_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_03_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_04_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_05_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_06_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_07_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_08_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_tit_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-標題'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_ctn_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='EN-內容'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_01_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_02_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_03_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_04_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_05_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_06_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_07_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_08_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_tit_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-標題'),
        ),
        migrations.AddField(
            model_name='bc_01',
            name='bc_cont_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='EN-主要產品說明'),
        ),
        migrations.AddField(
            model_name='bc_01',
            name='bc_img_001_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品圖片-1'),
        ),
        migrations.AddField(
            model_name='bc_01',
            name='bc_img_002_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品圖片-1'),
        ),
        migrations.AddField(
            model_name='bc_01',
            name='bc_img_003_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品圖片-1'),
        ),
        migrations.AddField(
            model_name='bc_01',
            name='bc_img_004_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品圖片-1'),
        ),
        migrations.AddField(
            model_name='bc_01',
            name='bc_img_005_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品圖片-1'),
        ),
        migrations.AddField(
            model_name='bc_01',
            name='bc_img_006_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品圖片-1'),
        ),
        migrations.AddField(
            model_name='bc_01',
            name='bc_img_007_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品圖片-1'),
        ),
        migrations.AddField(
            model_name='bc_01',
            name='bc_img_008_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品圖片-1'),
        ),
        migrations.AddField(
            model_name='bc_01',
            name='bc_img_009_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品圖片-1'),
        ),
        migrations.AddField(
            model_name='bc_01',
            name='bc_img_010_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品圖片-1'),
        ),
        migrations.AddField(
            model_name='bc_01',
            name='bc_tit_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品名稱'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_ctn_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='EN-內容'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_01_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_02_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_03_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_04_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_05_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_06_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_07_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_08_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_tit_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-標題'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_cont_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='EN-主要產品說明'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_img_001_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品圖片-1'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_seri_001_1_en',
            field=ckeditor.fields.RichTextField(blank=True, default='EN-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_seri_001_2_en',
            field=ckeditor.fields.RichTextField(blank=True, default='EN-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_seri_001_3_en',
            field=ckeditor.fields.RichTextField(blank=True, default='EN-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_seri_001_4_en',
            field=ckeditor.fields.RichTextField(blank=True, default='EN-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_seri_001_tit_01_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品系列-標題-1'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_seri_001_tit_02_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品系列-標題-2'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_seri_001_tit_03_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品系列-標題-3'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_seri_001_tit_04_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品系列-標題-4'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_tit_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-EN-產品名稱'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_ctn_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='EN-內容'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_01_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_02_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_03_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_04_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_05_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_06_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_07_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_08_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_tit_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-標題'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_ctn_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='EN-內容'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_01_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_02_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_03_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_04_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_05_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_06_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_07_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_08_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_tit_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-標題'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_ctn_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='EN-內容'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_01_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_02_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_03_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_04_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_05_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_06_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_07_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_08_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_tit_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-標題'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_ctn_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='EN-內容'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_01_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_02_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_03_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_04_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_05_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_06_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_07_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_08_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_tit_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-標題'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_cont_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='EN-主要產品說明'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_img_001_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品圖片-1'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_seri_001_1_en',
            field=ckeditor.fields.RichTextField(blank=True, default='EN-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_seri_001_2_en',
            field=ckeditor.fields.RichTextField(blank=True, default='EN-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_seri_001_3_en',
            field=ckeditor.fields.RichTextField(blank=True, default='EN-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_seri_001_4_en',
            field=ckeditor.fields.RichTextField(blank=True, default='EN-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_seri_001_tit_01_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品系列-標題-1'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_seri_001_tit_02_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品系列-標題-2'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_seri_001_tit_03_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品系列-標題-3'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_seri_001_tit_04_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品系列-標題-4'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_tit_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品名稱'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_cont_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='EN-主要產品說明'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_img_001_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品圖片-1'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_seri_001_1_en',
            field=ckeditor.fields.RichTextField(blank=True, default='EN-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_seri_001_2_en',
            field=ckeditor.fields.RichTextField(blank=True, default='EN-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_seri_001_3_en',
            field=ckeditor.fields.RichTextField(blank=True, default='EN-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_seri_001_4_en',
            field=ckeditor.fields.RichTextField(blank=True, default='EN-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_seri_001_tit_01_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品系列-標題-1'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_seri_001_tit_02_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品系列-標題-2'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_seri_001_tit_03_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品系列-標題-3'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_seri_001_tit_04_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品系列-標題-4'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_tit_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品名稱'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_cont_en',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='EN-主要產品說明'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_img_001_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品圖片-1'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_1_en',
            field=ckeditor.fields.RichTextField(blank=True, default='EN-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_2_en',
            field=ckeditor.fields.RichTextField(blank=True, default='EN-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_3_en',
            field=ckeditor.fields.RichTextField(blank=True, default='EN-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_4_en',
            field=ckeditor.fields.RichTextField(blank=True, default='EN-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_tit_01_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品系列-標題-1'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_tit_02_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品系列-標題-2'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_tit_03_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品系列-標題-3'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_tit_04_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品系列-標題-4'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_tit_en',
            field=models.CharField(blank=True, max_length=100000, verbose_name='EN-產品名稱'),
        ),
    ]
