# Generated by Django 3.2.5 on 2022-05-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herrmann', '0020_auto_20220516_0758'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bc_01',
        ),
    ]
