# Generated by Django 3.2.5 on 2022-06-01 08:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herrmann', '0021_delete_bc_01'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automation_01',
            options={'verbose_name': 'Branch-Automation', 'verbose_name_plural': 'Branch-Automation'},
        ),
        migrations.AlterModelOptions(
            name='automotive_01',
            options={'verbose_name': 'Branch-Automotive', 'verbose_name_plural': 'Branch-Automotive'},
        ),
        migrations.AlterModelOptions(
            name='battery_01',
            options={'verbose_name': 'Branch-Battery', 'verbose_name_plural': 'Branch-Battery'},
        ),
        migrations.AlterModelOptions(
            name='consumer_01',
            options={'verbose_name': 'Branch-Consumer', 'verbose_name_plural': 'Branch-Consumer'},
        ),
        migrations.AlterModelOptions(
            name='cpn_01',
            options={'ordering': ['id'], 'verbose_name': 'Ultrasonic Components', 'verbose_name_plural': 'Ultrasonic Components'},
        ),
        migrations.AlterModelOptions(
            name='electronics_01',
            options={'verbose_name': 'Branch-Electronics', 'verbose_name_plural': 'Branch-Electronics'},
        ),
        migrations.AlterModelOptions(
            name='food_01',
            options={'verbose_name': 'Branch-Food', 'verbose_name_plural': 'Branch-Food'},
        ),
        migrations.AlterModelOptions(
            name='hygiene_01',
            options={'verbose_name': 'Branch-Hygiene', 'verbose_name_plural': 'Branch-Hygiene'},
        ),
        migrations.AlterModelOptions(
            name='medical_01',
            options={'verbose_name': 'Branch-Medical', 'verbose_name_plural': 'Branch-Medical'},
        ),
        migrations.AlterModelOptions(
            name='mta_01',
            options={'ordering': ['id'], 'verbose_name': 'Ultrasonic Welding Metal', 'verbose_name_plural': 'Ultrasonic Welding Metal'},
        ),
        migrations.AlterModelOptions(
            name='sys_01',
            options={'ordering': ['id'], 'verbose_name': 'Ultrasonic Welding system', 'verbose_name_plural': 'Ultrasonic Welding system'},
        ),
        migrations.AlterModelOptions(
            name='welding_02',
            options={'ordering': ['id'], 'verbose_name': 'Ultrasonic Welding Machine', 'verbose_name_plural': 'Ultrasonic Welding Machine'},
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_ctn_sp',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='SP-內容'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_01_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_02_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_03_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_04_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_05_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_06_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_07_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_pho_08_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='automation_01',
            name='automation_tit_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-標題'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_ctn_sp',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='SP-內容'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_01_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_02_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_03_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_04_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_05_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_06_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_07_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_pho_08_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='automotive_01',
            name='automotive_tit_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-標題'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_ctn_sp',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='SP-內容'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_01_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_02_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_03_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_04_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_05_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_06_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_07_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_pho_08_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='battery_01',
            name='battery_tit_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-標題'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_ctn_sp',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='SP-內容'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_01_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_02_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_03_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_04_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_05_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_06_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_07_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_pho_08_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='consumer_01',
            name='consumer_tit_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-標題'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_cont_sp',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='SP-主要產品說明'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_img_001_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品圖片-1'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_seri_001_1_sp',
            field=ckeditor.fields.RichTextField(blank=True, default='SP-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_seri_001_2_sp',
            field=ckeditor.fields.RichTextField(blank=True, default='SP-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_seri_001_3_sp',
            field=ckeditor.fields.RichTextField(blank=True, default='SP-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_seri_001_4_sp',
            field=ckeditor.fields.RichTextField(blank=True, default='SP-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_seri_001_tit_01_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品系列-標題-1'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_seri_001_tit_02_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品系列-標題-2'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_seri_001_tit_03_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品系列-標題-3'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_seri_001_tit_04_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品系列-標題-4'),
        ),
        migrations.AddField(
            model_name='cpn_01',
            name='cpn_tit_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-SP-產品名稱'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_ctn_sp',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='SP-內容'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_01_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_02_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_03_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_04_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_05_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_06_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_07_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_pho_08_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='electronics_01',
            name='electronics_tit_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-標題'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_ctn_sp',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='SP-內容'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_01_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_02_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_03_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_04_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_05_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_06_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_07_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_pho_08_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='food_01',
            name='food_tit_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-標題'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_ctn_sp',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='SP-內容'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_01_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_02_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_03_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_04_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_05_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_06_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_07_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_pho_08_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='hygiene_01',
            name='hygiene_tit_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-標題'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_tit_013',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-左上-標題'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_tit_014',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-中上-標題'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_tit_015',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-右上-標題'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_tit_016',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-左下-標題'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_tit_017',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-中下-標題'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_tit_018',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-右下-標題'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_txt_013',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-左上'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_txt_014',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-中上'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_txt_015',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-右上'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_txt_016',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-左下'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_txt_017',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-中下'),
        ),
        migrations.AddField(
            model_name='index_01',
            name='mid_txt_018',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-右下'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_ctn_sp',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='SP-內容'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_01_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_02_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_03_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_04_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_05_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_06_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_07_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_pho_08_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-圖片'),
        ),
        migrations.AddField(
            model_name='medical_01',
            name='medical_tit_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-標題'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_cont_sp',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='SP-主要產品說明'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_img_001_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品圖片-1'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_seri_001_1_sp',
            field=ckeditor.fields.RichTextField(blank=True, default='SP-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_seri_001_2_sp',
            field=ckeditor.fields.RichTextField(blank=True, default='SP-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_seri_001_3_sp',
            field=ckeditor.fields.RichTextField(blank=True, default='SP-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_seri_001_4_sp',
            field=ckeditor.fields.RichTextField(blank=True, default='SP-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_seri_001_tit_01_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品系列-標題-1'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_seri_001_tit_02_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品系列-標題-2'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_seri_001_tit_03_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品系列-標題-3'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_seri_001_tit_04_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品系列-標題-4'),
        ),
        migrations.AddField(
            model_name='mta_01',
            name='mta_tit_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品名稱'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_cont_sp',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='SP-主要產品說明'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_img_001_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品圖片-1'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_seri_001_1_sp',
            field=ckeditor.fields.RichTextField(blank=True, default='SP-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_seri_001_2_sp',
            field=ckeditor.fields.RichTextField(blank=True, default='SP-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_seri_001_3_sp',
            field=ckeditor.fields.RichTextField(blank=True, default='SP-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_seri_001_4_sp',
            field=ckeditor.fields.RichTextField(blank=True, default='SP-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_seri_001_tit_01_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品系列-標題-1'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_seri_001_tit_02_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品系列-標題-2'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_seri_001_tit_03_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品系列-標題-3'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_seri_001_tit_04_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品系列-標題-4'),
        ),
        migrations.AddField(
            model_name='sys_01',
            name='sys_tit_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品名稱'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_cont_sp',
            field=ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='SP-主要產品說明'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_img_001_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品圖片-1'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_1_sp',
            field=ckeditor.fields.RichTextField(blank=True, default='SP-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_2_sp',
            field=ckeditor.fields.RichTextField(blank=True, default='SP-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_3_sp',
            field=ckeditor.fields.RichTextField(blank=True, default='SP-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_4_sp',
            field=ckeditor.fields.RichTextField(blank=True, default='SP-文字敘述', max_length=1000000, null=True, verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_tit_01_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品系列-標題-1'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_tit_02_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品系列-標題-2'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_tit_03_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品系列-標題-3'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_seri_001_tit_04_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品系列-標題-4'),
        ),
        migrations.AddField(
            model_name='welding_02',
            name='welding_tit_sp',
            field=models.CharField(blank=True, max_length=100000, verbose_name='SP-產品名稱'),
        ),
    ]
