# Generated by Django 3.2.5 on 2022-06-08 08:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herrmann', '0022_auto_20220601_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_txt_001', ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='內容')),
                ('about_txt_001_en', ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='內容')),
                ('about_txt_001_sp', ckeditor.fields.RichTextField(blank=True, max_length=100000, verbose_name='內容')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
    ]
