# Generated by Django 3.2.5 on 2023-03-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herrmann', '0023_about_01'),
    ]

    operations = [
        migrations.CreateModel(
            name='pla_index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pla_index_001', models.CharField(blank=True, max_length=100000, verbose_name='輪播圖片-1')),
                ('pla_index_002', models.CharField(blank=True, max_length=100000, verbose_name='輪播圖片-2')),
                ('pla_index_003', models.CharField(blank=True, max_length=100000, verbose_name='輪播圖片-3')),
                ('pla_index_004', models.CharField(blank=True, max_length=100000, verbose_name='輪播圖片-4')),
                ('pla_index_005', models.CharField(blank=True, max_length=100000, verbose_name='輪播圖片-5')),
            ],
            options={
                'verbose_name': 'plastic-home',
                'verbose_name_plural': 'plastic-home',
            },
        ),
    ]
